config/routes.rb
 Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resource :wechats, only: [:show, :create]

  devise_for :users
  resources :feedbacks
  resources :courses
  resources :tasks
  resources :materials
  resources :surveys
  resources :students
  resources :credits
  root to: 'site#index'

  get 'index' => 'site#index'
  get 'books' => 'site#books'
  get 'course' => 'site#course'
  get 'teacher' => 'site#teacher'
  get 'article' => 'site#article'
  get 'about' => 'site#about'
  get 'feedback' => 'site#feedback'
  # get 'task' => 'tasks#tasks'

  #match ':controller(/:action(/:id(.:format)))', :via => :all

end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :student
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  layout 'wechat'
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url, notice: 'Credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:score, :student_id)
    end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_form.html.slim
= simple_form_for(@credit) do |f|
  = f.error_notification

  .form-inputs
    = f.input :score
    = f.association :student

  .form-actions
    = f.button :submit

app/views/credits/edit.html.slim
h1 Editing credit

== render 'form'

= link_to 'Show', @credit
'  |
= link_to 'Back', credits_path

app/views/credits/index.html.slim
h1 Listing credits

table
  thead
    tr
      th Score
      th Student
      th
      th
      th

  tbody
    - @credits.each do |credit|
      tr
        td = credit.score
        td = credit.student
        td = link_to 'Show', credit
        td = link_to 'Edit', edit_credit_path(credit)
        td = link_to 'Destroy', credit, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Credit', new_credit_path

app/views/credits/index.slim
doctype html
html
  head
    meta[http-equiv="Content-Type" content="text/html; charset=utf-8"]
    meta[content="initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no,width=device-width" name="viewport"]
    meta[name="format-detection" content="telephone=no"]
    title
      | 职业说careerwhisper
    link[href="css/bootstrap.min.css" rel="stylesheet"]
    link[rel="stylesheet" type="text/css" href="css/wechat.css"]
  body
    .container
      h3.text-center.titles
        | 积分排行
      .credits
        ul.nav.nav-tabs
          li.active
            a[href="#"]
              | 上周积分
          li
            a[href="#"]
              | 总积分
        .table_box
          table.table.table-bordered.text-center
            thead
              tr
                th
                  | 姓名
                th
                  | 积分
                th
                  | 排名
            tbody
              tr
                td
                  | 张三
                td
                  | 20
                td
                  | 10
              tr
                td
                  | 李四
                td
                  | 40
                td
                  | 22
              tr
                td
                  | 王五
                td
                  | 30
                td
                  | 33
          table.table.table-bordered.text-center
            thead
              tr
                th
                  | 姓名
                th
                  | 积分
                th
                  | 排名
            tbody
              tr
                td
                  | Tanmay
                td
                  | Bangalore
                td
                  | 560002
              tr
                td
                  | Sachin
                td
                  | Mumbai
                td
                  | 400003
              tr
                td
                  | Uma
                td
                  | Pune
                td
                  | 411027
  script[src="js/jquery.min.js" type="text/javascript" charset="utf-8"]
  script[type="text/javascript"]
    |  $(".credits .nav li").click(function(){ $(this).addClass("active").siblings().removeClass("active"); var index=$(this).index(); $(".credits .table").eq(index).show().siblings().hide() }) 

app/views/credits/new.html.slim
h1 New credit

== render 'form'

= link_to 'Back', credits_path

app/views/credits/show.html.slim
p#notice = notice

p
  strong Score:
  = @credit.score
p
  strong Student:
  = @credit.student

= link_to 'Edit', edit_credit_path(@credit)
'  |
= link_to 'Back', credits_path