config/routes.rb
 Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resource :wechats, only: [:show, :create]

  devise_for :users
  resources :feedbacks
  resources :courses
  resources :tasks
  resources :materials
  resources :surveys
  resources :students
  resources :credits
  root to: 'site#index'

  get 'index' => 'site#index'
  get 'books' => 'site#books'
  get 'course' => 'site#course'
  get 'teacher' => 'site#teacher'
  get 'article' => 'site#article'
  get 'about' => 'site#about'
  get 'feedback' => 'site#feedback'
  # get 'task' => 'tasks#tasks'

  #match ':controller(/:action(/:id(.:format)))', :via => :all

end

app/models/survey.rb
class Survey < ApplicationRecord
  has_paper_trail
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  layout 'apps', :except => :index
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def after_sign_in_path_for(resource_or_scope)
    request.referrer
  end
  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  # GET /surveys
  # GET /surveys.json
  def index
    set_meta_tags title: '问卷列表'

    @surveys = Survey.all

    render layout:"wechat"
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :description, :href, :start_at, :end_at)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.slim
= simple_form_for(@survey) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :href
    = f.input :start_at
    = f.input :end_at

  .form-actions
    = f.button :submit

app/views/surveys/edit.html.slim
h1 Editing survey

== render 'form'

= link_to 'Show', @survey
'  |
= link_to 'Back', surveys_path

app/views/surveys/index.html.slim
ul.material[style="margin:0 6px"]
  - @surveys.each do |survey|
    li
      h5
        = survey.name
      p.text-justify
        = survey.description
      div
        i
          = survey.start_at
        a[href=survey.href]
          img[src="images/downIcon.png"]

app/views/surveys/new.html.slim
h1 New survey

== render 'form'

= link_to 'Back', surveys_path

app/views/surveys/show.html.slim
p#notice = notice

p
  strong Name:
  = @survey.name
p
  strong Description:
  = @survey.description
p
  strong Href:
  = @survey.href
p
  strong Start at:
  = @survey.start_at
p
  strong End at:
  = @survey.end_at

= link_to 'Edit', edit_survey_path(@survey)
'  |
= link_to 'Back', surveys_path