config/routes.rb
 Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resource :wechats, only: [:show, :create]

  devise_for :users
  resources :feedbacks
  resources :courses
  resources :tasks
  resources :materials
  resources :surveys
  resources :students
  resources :credits
  root to: 'site#index'

  get 'index' => 'site#index'
  get 'books' => 'site#books'
  get 'course' => 'site#course'
  get 'teacher' => 'site#teacher'
  get 'article' => 'site#article'
  get 'about' => 'site#about'
  get 'feedback' => 'site#feedback'
  # get 'task' => 'tasks#tasks'

  #match ':controller(/:action(/:id(.:format)))', :via => :all

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  layout 'devise'
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def after_sign_in_path_for(resource_or_scope)
    request.referrer
  end
  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    set_meta_tags title: '意见反馈'

    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    set_meta_tags title: '意见反馈'

    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)
    @feedback.user_id = current_user.id

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: '提交成功！' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:description, :user_id)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.slim
= simple_form_for(@feedback) do |f|
  = f.error_notification
  
  .form-inputs
    = f.text_area :description, :label=>"描述", :rows => 10, style: 'width:100%'
    / = f.association :user

  .form-actions
    = f.button :submit, :value=>'提交', class:"btn btn-success btn-block"

app/views/feedbacks/edit.html.slim
h1 Editing feedback

== render 'form'

= link_to 'Show', @feedback
'  |
= link_to 'Back', feedbacks_path

app/views/feedbacks/feedback.slim
doctype html
html
  head
    meta[http-equiv="Content-Type" content="text/html; charset=utf-8"]
    meta[content="initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no,width=device-width" name="viewport"]
    meta[name="format-detection" content="telephone=no"]
    title
      | 职业说careerwhisper
    link[href="css/bootstrap.min.css" rel="stylesheet"]
    link[rel="stylesheet" type="text/css" href="css/wechat.css"]
  body
    .container
      .feedback
        form#forms[action=""]
          p.form-group
            label[for=""]
              | 联系方式:
            input#phone.form-control[type="text" name="" value=""]
          p.form-group
            label[for=""]
              | 反馈内容:
            textarea#problem.form-control[name="" rows="6" cols="38"]
          button#btnsubmit.btn.btn-primary.btn-sm[type="button"]
            | 提交
  script[src="js/jquery.min.js" type="text/javascript" charset="utf-8"]
  script[type="text/javascript"]
    |  $(function(){ // 工具方法 function isEmpty(tmp) { return tmp == null || tmp == ""; } $("#btnsubmit").click(function () { var phone = $("#phone").val(); var phoneReg = /^[1-9]{1}[0-9]{10}$/; if(isEmpty(phone) || !phoneReg.test(phone)) { // 提示 alert('请输入正确电话号码'); return false; } var name = $("#problem").val(); if(isEmpty(name)) { alert('请输入问题描述'); // 提示 return false; } $("#forms").submit(); }); }) 

app/views/feedbacks/index.html.slim
h1 Listing feedbacks

table
  thead
    tr
      th Description
      th User
      th
      th
      th

  tbody
    - @feedbacks.each do |feedback|
      tr
        td = feedback.description
        td = feedback.user
        td = link_to 'Show', feedback
        td = link_to 'Edit', edit_feedback_path(feedback)
        td = link_to 'Destroy', feedback, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Feedback', new_feedback_path

app/views/feedbacks/new.html.slim
== render 'form'

/ = link_to 'Back', feedbacks_path

app/views/feedbacks/show.html.slim
p#notice = notice

.row.text-center
  .row
    | 描述:
  .row
    = @feedback.description
.row.text-center
  .row
    | 用户:
  .row
    = @feedback.user.email

/ = link_to 'Edit', edit_feedback_path(@feedback)
/ '  |
/ = link_to 'Back', feedbacks_path